inherit_from: .rubocop_todo.yml
AllCops:
    NewCops: enable
Style/MixinUsage:
    Enabled: false
Style/Documentation:
    Enabled: false
Style/StringLiterals:
    Enabled: false
Style/AsciiComments:
     Enabled: false
Layout/LineLength:
    Enabled: false
Metrics/MethodLength:
    Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
